### ISSUE TITLE
Almost no goods are sold in the office area.

### ISSUE THREAD

**Issue by AinzRimuru** [Adwozo/adwozo-mod-cities-ProfitBasedIndustryAndOffice#4]
Almost no goods are sold in the office area, and inventory accumulation is so serious that there is almost no tax revenue and serious losses.

The export of intangible goods is not affected by traffic, so it should be able to be sold smoothly, but this is not the case.
I'm not sure if this is related to the bug where the office area was overstocked and ended up with only 5 employees in the building.

**Comment by AinzRimuru** [comment]
I will provide my archive if necessary. I am using and only using the latest version of this mod. I didn't pay attention to this problem before, at least in the historical version, even if there is a problem, it is not serious.

**Comment by Adwozo** [comment]
which version are you using? master branch, dev branch? screenshot and save file would be helpful as well, thanks. I am not able to replicate this problem in my save using tag 1.4.0 commit.

**Comment by AinzRimuru** [comment]
The version is 1.3.1
I reverted to 1.2.6 and things became normal.
Noticed that you have updated to 1.4.0, I will test it later

**Comment by Adwozo** [comment]
thanks, let me know the result~!

**Comment by AinzRimuru** [comment]
Problem fixed.
